version: '3'

services:
  app:
    build: .
    container_name: app
    tty: true
    volumes:
      - .:/go/src
    ports:
      - "8888:8888"
      
  db:
    image: postgres:9.4
    container_name: db
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=catalog
    ports:
      - "5432:5432"